'use client'

/**
 * Tooltip metadata for field hints
 * Displayed as a help icon (?) next to the label with popover on hover
 */
export interface FieldTooltipMeta {
  /** Tooltip title */
  title?: string
  /** Main tooltip text (required) */
  description: string
  /** Example of good input */
  example?: string
  /** Impact on result (e.g., "More categories = more students") */
  impact?: string
}

/**
 * All available field types for use in fieldType
 * Used for explicitly specifying field type in Zod .meta({ ui: { fieldType: '...' } })
 */
export type FieldComponentType =
  // Text fields
  | 'string'
  | 'textarea'
  | 'password'
  | 'passwordStrength'
  | 'editable'
  | 'richText'
  // Number fields
  | 'number'
  | 'numberInput'
  | 'slider'
  | 'rating'
  | 'currency'
  | 'percentage'
  // Date and time
  | 'date'
  | 'time'
  | 'dateRange'
  | 'dateTimePicker'
  | 'duration'
  | 'schedule'
  // Boolean fields
  | 'checkbox'
  | 'switch'
  // Selection from list
  | 'select'
  | 'nativeSelect'
  | 'combobox'
  | 'autocomplete'
  | 'listbox'
  | 'radioGroup'
  | 'radioCard'
  | 'segmentedGroup'
  | 'checkboxCard'
  | 'tags'
  // Specialized fields
  | 'phone'
  | 'address'
  | 'pinInput'
  | 'otpInput'
  | 'colorPicker'
  | 'fileUpload'
  | 'maskedInput'
  // Вычисляемые поля
  | 'calculated'
  // Поля для опросников
  | 'matrixChoice'
  | 'imageChoice'
  | 'likert'
  | 'yesNo'
  // Табличный редактор
  | 'tableEditor'

/**
 * Option for select/enum fields with i18n support
 */
export interface FieldOptionMeta {
  /** Option value */
  value: string | number
  /** Display text (fallback if no translation available) */
  label: string
  /** Option is disabled */
  disabled?: boolean
  /** i18n key for label translation (e.g., 'Category.ELECTRONICS') */
  i18nKey?: string
}

/**
 * UI metadata from Zod schema .meta()
 */
export interface FieldUIMeta {
  title?: string
  description?: string
  placeholder?: string
  /** Tooltip for hint next to label */
  tooltip?: FieldTooltipMeta
  /**
   * Explicit field component type specification
   * Takes priority over auto-detection from Zod type
   * @example fieldType: 'richText' for rich editor instead of plain string
   */
  fieldType?: FieldComponentType
  /**
   * Additional props for specific field type
   * @example { countries: ['RU', 'US'] } for phone
   */
  fieldProps?: Record<string, unknown>
  /**
   * Options for select/enum fields (generated from @form.* directives)
   * Supports i18n via i18nKey in each option
   */
  options?: FieldOptionMeta[]
  /**
   * i18n key for translating UI texts
   * Generated by zenstack-form-plugin when i18n: true
   *
   * Format: "ModelName.fieldName"
   * Full keys: "ModelName.fieldName.title", "ModelName.fieldName.placeholder", etc.
   *
   * @example i18nKey: 'Product.name' -> translations in Product.name.title, Product.name.placeholder
   */
  i18nKey?: string
  /**
   * HTML autocomplete атрибут.
   * Override автоматического определения по имени поля.
   * Установите 'off' для отключения автозаполнения.
   *
   * @example autocomplete: 'street-address'
   * @example autocomplete: 'off'
   * @see https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls
   */
  autocomplete?: string
}
